    /** 教师Id     */ protected Integer   autoId    ;
    /** 教师编号   */ protected String    nO        ;
    /** 教师密码   */ protected String    password  ;
    /** 教师姓名   */ protected String    name      ;
    /** 教师性别   */ protected String    sex       ;
    /** 学部Id     */ protected Integer   depId     ;
    /** 教研组Id   */ protected Integer   rshId     ;
    /** 出生日期   */ protected Timestamp birthday  ;
    /** 出生地     */ protected String    birthPlace;
    /** 证件类型   */ protected Integer   cardType  ;
    /** 证件号码   */ protected String    cardNO    ;
    /** 政治面貌   */ protected String    political ;
    /** EMAIL      */ protected String    email     ;
    /** 联系电话   */ protected String    phone     ;
    /** 备注       */ protected String    remark    ;
    /** 监考类型   */ protected Byte      monitor   ;
    /** 教师状态   */ protected Byte      state     ;
    /** 用户Id     */ protected Integer   userId    ;
    /** 学部名称   */ protected String    depName   ;
    /** 教研组名称 */ protected String    rshName   ;
    /** 名称       */ protected String    cardTypeNm;
